ruby-site/config/routes.rb
Rails.application.routes.draw do
  resources :cylinders
  root to: 'visitors#index'
  devise_for :users
  resources :users

  post '/search' => "cylinders#search", :as => :search

  devise_scope :user do
    get '/users/sign-in' => "devise/sessions#new", :as => :login
  end

  devise_scope :user do
  	get '/users/edit' => "devise/sessions#edit", :as => :edit
  end
end

ruby-site/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby-site/app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

ruby-site/app/models/cylinder.rb
class Cylinder < ApplicationRecord
	has_many :user_cylinders
	has_many :users, :through => :user_cylinders

	# try 2
	#include Filterable

	# try 1
	# here or in controller?
	def self.search(search)
	  search_condition = "%" + search + "%"
	  #byebug
	  Cylinder.where(:conditions => ['pin LIKE ? OR valve LIKE ?', search_condition, search_condition])
	end

end

ruby-site/app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :maintenance, :manufacturer, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :user_cylinders
  has_many :cylinders, :through => :user_cylinders

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

ruby-site/app/models/user_cylinder.rb
class UserCylinder < ApplicationRecord
  belongs_to :user
  belongs_to :cylinder
end

ruby-site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def ensure_authentication
  	# check this (do you need all roles?)
  	unless user_signed_in? #or admin_signed_in?
  		redirect_to login_path, alert: "You have to be signed in" and return
  	end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

ruby-site/app/controllers/cylinders_controller.rb
class CylindersController < ApplicationController
  # ensure auth before anyone sees
  before_action :ensure_authentication
  before_action :product_owner_only, only: [:show, :edit, :update, :destroy]

  # before you can check who owns cylinder, set cylinder
  before_action :set_cylinder, only: [:show, :edit, :update, :destroy]

  # search for cylinders (pin or valve pin ?)
  def search
    search_condition = "%" + search + "%"
    byebug
    @cylinder = Cylinder.where(:conditions => ['pin LIKE ? OR valve LIKE ?', search_condition, search_condition])
    byebug
    #@cylinder = Cylinder.search params[:search]
  end

  # GET /cylinders
  # GET /cylinders.json
  def index
    if current_user.admin?
      @cylinders = Cylinder.all
    else
      @cylinders = current_user.cylinders
    end
  end

  # GET /cylinders/1
  # GET /cylinders/1.json
  def show
  end

  # GET /cylinders/new
  def new
    @cylinder = Cylinder.new
  end

  # GET /cylinders/1/edit
  def edit
  end

  # POST /cylinders
  # POST /cylinders.json
  def create
    @cylinder = Cylinder.new(cylinder_params)
    @cylinder.user = current_user

    # create the user-to-cylinder mapping
    uc = UserCylinder.new
    uc.cylinder = @cylinder
    uc.user = current_user
    uc.save!

    respond_to do |format|
      if @cylinder.save
        format.html { redirect_to @cylinder, notice: 'Cylinder was successfully created.' }
        format.json { render :show, status: :created, location: @cylinder }
      else
        format.html { render :new }
        format.json { render json: @cylinder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cylinders/1
  # PATCH/PUT /cylinders/1.json
  def update
    respond_to do |format|
      if @cylinder.update(cylinder_params)
        format.html { redirect_to @cylinder, notice: 'Cylinder was successfully updated.' }
        format.json { render :show, status: :ok, location: @cylinder }
      else
        format.html { render :edit }
        format.json { render json: @cylinder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cylinders/1
  # DELETE /cylinders/1.json
  def destroy
    @cylinder.destroy
    respond_to do |format|
      format.html { redirect_to cylinders_url, notice: 'Cylinder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cylinder
      @cylinder = Cylinder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cylinder_params
      params.require(:cylinder).permit(:pin, :valve, :production, :gas, :pressure, :project, :vender, :manufacturer, :agency, :user, :mac, :location)
    end

    def product_owner_only
      @cylinder = Cylinder.find(params[:id])
      unless @cylinder.users.include?(current_user) or current_user.admin?
      #unless (signed_in? and current_user == @cylinder.user) or current_user.admin?
        redirect_to cylinders_url, alert: "You don't have permission to access this cylinder" and return
      end
    end

end

ruby-site/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

ruby-site/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

ruby-site/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby-site/app/helpers/cylinders_helper.rb
module CylindersHelper
end

ruby-site/app/views/cylinders/_form.html.erb
<%= form_for(cylinder) do |f| %>
  <% if cylinder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cylinder.errors.count, "error") %> prohibited this cylinder from being saved:</h2>

      <ul>
      <% cylinder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pin %>
    <%= f.text_field :pin %>
  </div>

  <div class="field">
    <%= f.label :valve, 'Valve PIN' %>
    <%= f.text_field :valve %>
  </div>

  <div class="field">
    <%= f.label :production %>
    <%= f.date_select :production,
          :start_year => 1970,
          :end_year => 2030 %>
  </div>

  <div class="field">
    <%= f.label :gas %>
    <%= f.select :gas, ['Hydrogen', 'Helium', 'N2'] %>
  </div>

  <div class="field">
    <%= f.label :pressure, "Pressure (MPa)" %>
    <%= f.text_field :pressure %>
  </div>

  <div class="field">
    <%= f.label :project, "Project Number" %>
    <%= f.text_field :project %>
  </div>

  <div class="field">
    <%= f.label :vender, 'Vendor' %>
    <%= f.text_field :vender %>
  </div>

  <div class="field">
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer %>
  </div>

  <div class="field">
    <%= f.label :agency %>
    <%= f.text_field :agency %>
  </div>

  <div class="field">
    <%= f.label :mac, 'MAC' %>
    <%= f.text_field :mac %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :user %>
    <%= f.text_field :user, :value => 'n/a' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby-site/app/views/cylinders/_search.html.erb
<%-#= form_tag :controller => 'cylinder', :action => 'search' :method => 'post' do %>
<%-#= form_for(cylinder) do |f| %>
<%= form_tag("/search", method: "get") do %>
	<%= text_field_tag :search, params[:search], :id => 'search_field' %>
	<%= submit_tag "Search", :name => nil %> 
	<%-#= link_to_function "Clear", "$('search_field').clear()" %>
<% end %> 

ruby-site/app/views/cylinders/edit.html.erb
<h1>Editing Cylinder</h1>

<%= render 'form', cylinder: @cylinder %>

<%= link_to 'Show', @cylinder %> |
<%= link_to 'Back', cylinders_path %>

ruby-site/app/views/cylinders/index.html.erb
<p id="notice"><%= notice %></p>

<div class="headline">
<h1>Cylinders</h1>

<% if false %>

<%= render 'search', cylinder: @cylinder %>

<%# else %>

<div id="search">
  <%= render :partial => 'search' %>
</div>

<% end %>

<% if false %>

<ul>
  <% @grants.each do |grant| %>
<li><%= link_to grant.title, 
  :action => 'show', :id => grant.id  %></li>
<% end %>
</ul>

<% end %>

<p><%= link_to 'New Cylinder', new_cylinder_path %></p>
</div>

<br>
<br>
<br>
<br>
<br>

<div style="overflow: auto;">
<table>
  <thead>
    <tr>
      <th>PIN</th>
      <th>Valve #</th>
      <th>Production</th>
      <th>Gas</th>
      <th>Pressure</th>
      <th>Project #</th>
      <th>Vendor</th>
      <th>Manufacturer</th>
      <th>Agency</th>
      <th>User</th>
      <th>MAC</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cylinders.each do |cylinder| %>
      <tr>
        <td><%= cylinder.pin %></td>
        <td><%= cylinder.valve %></td>
        <td><%= cylinder.production %></td>
        <td><%= cylinder.gas %></td>
        <td><%= cylinder.pressure %></td>
        <td><%= cylinder.project %></td>
        <td><%= cylinder.vender %></td>
        <td><%= cylinder.manufacturer %></td>
        <td><%= cylinder.agency %></td>
        <td><%= cylinder.user %></td>
        <td><%= cylinder.mac %></td>
        <td><%= cylinder.location %></td>

        <td><%= link_to 'Info', cylinder %></td>
        <% if current_user.admin? or current_user.maintenance? or current_user.manufacturer? %>
        <td><%= link_to 'Edit', edit_cylinder_path(cylinder) %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Remove', cylinder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

ruby-site/app/views/cylinders/new.html.erb
<h1>New Cylinder</h1>

<%= render 'form', cylinder: @cylinder %>

<%= link_to 'Back', cylinders_path %>

ruby-site/app/views/cylinders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pin:</strong>
  <%= @cylinder.pin %>
</p>

<p>
  <strong>Valve:</strong>
  <%= @cylinder.valve %>
</p>

<p>
  <strong>Production:</strong>
  <%= @cylinder.production %>
</p>

<p>
  <strong>Gas:</strong>
  <%= @cylinder.gas %>
</p>

<p>
  <strong>Pressure (MPa):</strong>
  <%= @cylinder.pressure %>
</p>

<p>
  <strong>Project:</strong>
  <%= @cylinder.project %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @cylinder.vender %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @cylinder.manufacturer %>
</p>

<p>
  <strong>Agency:</strong>
  <%= @cylinder.agency %>
</p>

<p>
  <strong>MAC:</strong>
  <%= @cylinder.mac %>
</p>

<p>
  <strong>Location:</strong>
  <%= @cylinder.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @cylinder.user %>
</p>

<%= link_to 'Edit', edit_cylinder_path(@cylinder) %> |
<%= link_to 'Back', cylinders_path %>

ruby-site/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

ruby-site/app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
<% if false %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% end %>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Cylinders', cylinders_path %></li>

  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% end %>

ruby-site/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

ruby-site/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if false %>
<li><%= link_to 'About', page_path('about') %></li>
<% end %>

ruby-site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tyco International" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tyco International" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

ruby-site/app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

ruby-site/app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

ruby-site/app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

ruby-site/app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

ruby-site/app/views/visitors/index.html.erb
<h2>Tyco International</h2>
<h5>Inventory Management</h5>
<% if not signed_in? %>
<p><%= link_to "Sign In", login_path %></p>
<% else %>
<p><%= link_to "View your Inventory", cylinders_url %></p>
<p><%= link_to "Manage Account", edit_path %></p>
<% end %>